name: my custom workflow
on: [push,fork]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Welcome Message
      run: echo "This is the first Message"
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        ref: main
    - name: List the files
      run: ls
    - name: Read the readme file
      run: cat README.md


